private ["_Secondary"];
canAbort = true;
_Secondary = currentWeapon player;
player addEventHandler ["fired", {if (alive player) then { player SetDamage 1.1;};}];
cutText [format["I think I may have to kill myself... 10 Seconds"], "PLAIN DOWN"];
sleep 4;
cutText [format["I cant take this cruel world... 6 Seconds"], "PLAIN DOWN"];
sleep 4;
cutText [format["Screw this shit... 2 Seconds"], "PLAIN DOWN"];
sleep 2;
cutText [format["No turning back now!"], "PLAIN DOWN"];
canAbort = false;
player playmove "ActsPercMstpSnonWpstDnon_suicide1B";
sleep 8.4;
player fire _Secondary;
player setdamage 1.0;